
##fetch all products
GET http://localhost:3000/products/

####create a products
POST http://localhost:3000/products/
Content-Type: application/json

{
 "name":"iPhone 8",
 "price":499
}

####fetch a single product
GET http://localhost:3000/products/601369c39104742b60c12b94

####update a single product
PATCH http://localhost:3000/products/{id}

####delete a single product
DELETE http://localhost:3000/products/{id}

####error route
GET http://localhost:3000/xyz


